language: python
python:
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
# command to install dependencies
install:
  - python -m pip install --upgrade pip==8.1.2
  - pip install cython
  - pip install numpy
  - pip install scipy
  - pip install -r requirements.txt
  - pip install nose
# command to run tests
script: nosetests